apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redbot
  namespace: redbot
spec:
  chart:
    spec:
      chart: app-template
      version: 0.2.1
      sourceRef:
        kind: HelmRepository
        name: elfhosted
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: redbot
  values:
    global:
      nameOverride: redbot
    image:
      repository: phasecorex/red-discordbot
      tag: latest@sha256:428c0f8242a4c5416b77f6d283fb3b6da094e7d1c045712b9c49ab182027c292
    securityContext:
      seccompProfile:
        type: RuntimeDefault
      # readOnlyRootFilesystem: true
    podSecurityContext:
      seccompProfile:
        type: RuntimeDefault
      # runAsUser: 568
      # runAsGroup: 568
      # fsGroup: 568
      allowPrivilegeEscalation: false
      # runAsNonRoot: true
      capabilities:
        drop:
        - ALL        
    automountServiceAccountToken: false
    controller:
      replicas: 1
      strategy: Recreate
      annotations:
        configmap.reloader.stakater.com/reload: "redbot-env"
        secret.reloader.stakater.com/reload: "redbot-env"
    persistence:
      config:
        enabled: true
        type: custom
        mountPath: /data/
        volumeSpec:
          persistentVolumeClaim:
            claimName: redbot
    envFrom:
    - secretRef:
        name: redbot-env 
    - configMapRef:
        name: redbot-env 
    resources:
      requests:
        cpu: 1m
        memory: 50Mi
        ephemeral-storage: 50Mi
      limits:
        cpu: 1
        memory: 512Mi
        ephemeral-storage: 100Mi        
    ingress:
      main:
        enabled: false
    service:
      main:
        enabled: false
